#include "common.h"
#include "adc.h"

void adc_power_on(void)
{
	SETBIT(ADCR, ADC_POWER_BIT);
}

void adc_power_off(void)
{
	CLEARBIT(ADCR, ADC_POWER_BIT);
}

void adc_select_multiple_channels(int ch)
{
	CLEARBITS(ADCR, ADC_CHANNEL_MASK);
	SETBITS(ADCR, (ch << ADC_CHANNEL_SHIFT) & ADC_CHANNEL_MASK);
}

void adc_select_single_channel(int ch)
{
	CLEARBITS(ADCR, ADC_CHANNEL_MASK);
	SETBIT(ADCR, ch);
}

void adc_start(int mode)
{
	CLEARBITS(ADCR, ADC_START_MASK);
	SETBITS(ADCR, (mode << ADC_START_SHIFT) & ADC_START_MASK);
}

void adc_start_sw(int ch)
{
	adc_select_single_channel(ch);
	adc_start(ADC_START_SW_MODE);
}

void adc_set_precision(int bits)
{
// 000 - 10bits/11clks,... 111 - 3bits/4clks
	CLEARBITS(ADCR, ADC_CLKS_MASK);
	SETBITS(ADCR, ((10 - bits) << ADC_CLKS_SHIFT) & ADC_CLKS_MASK);
}

void adc_set_clkdiv(int div)
{
	CLEARBITS(ADCR, ADC_CLKDIV_MASK);
	SETBITS(ADCR, (div << ADC_CLKDIV_SHIFT) & ADC_CLKDIV_MASK);
}

void adc_init(void)
{
	//CLKDIV = peripheral_cloch() / ADC_MAX_FREQ; // + 1	/* int div correction */ -1 /* by def CLKDIV */
	adc_set_clkdiv(peripheral_clock() / ADC_MAX_FREQ);
	adc_set_precision(8);
	adc_power_on();		
}

int adc_ready(void)
{
	return TESTBIT(ADDR, ADC_DONE_BIT);
//	unsigned int addr = ADDR;
//	return (addr & 0x80000000) >> 31;
}

int adc_channel(void)
{
	return (ADDR & ADC_CHN_MASK) >> ADC_CHN_SHIFT;
}

int adc_value(void)
{
	return (ADDR & ADC_VALUE_MASK) >> ADC_VALUE_SHIFT;
}

void adc_ch0_init(void)
{
	CLEARBIT(ADC_CH0_GPIO_DIR, ADC_CH0_GPIO_BIT);
	SETBIT(ADC_CH0_PINSEL_REG, ADC_CH0_PINSEL_BIT0);
	CLEARBIT(ADC_CH0_PINSEL_REG, ADC_CH0_PINSEL_BIT1);
}

void adc_ch1_init(void)
{
	CLEARBIT(ADC_CH1_GPIO_DIR, ADC_CH1_GPIO_BIT);
	SETBIT(ADC_CH1_PINSEL_REG, ADC_CH1_PINSEL_BIT0);
	CLEARBIT(ADC_CH1_PINSEL_REG, ADC_CH1_PINSEL_BIT1);
}

void adc_ch2_init(void)
{
	CLEARBIT(ADC_CH2_GPIO_DIR, ADC_CH2_GPIO_BIT);
	SETBIT(ADC_CH2_PINSEL_REG, ADC_CH2_PINSEL_BIT0);
	CLEARBIT(ADC_CH2_PINSEL_REG, ADC_CH2_PINSEL_BIT1);
}

void adc_ch3_init(void)
{
	CLEARBIT(ADC_CH3_GPIO_DIR, ADC_CH3_GPIO_BIT);
	SETBIT(ADC_CH3_PINSEL_REG, ADC_CH3_PINSEL_BIT0);
	CLEARBIT(ADC_CH3_PINSEL_REG, ADC_CH3_PINSEL_BIT1);
}

void adc_ch0_set(void)
{
	CLEARBIT(ADC_CH0_PINSEL_REG, ADC_CH0_PINSEL_BIT0);
	CLEARBIT(ADC_CH0_PINSEL_REG, ADC_CH0_PINSEL_BIT1);
	SETBIT(ADC_CH0_GPIO_DIR, ADC_CH0_GPIO_BIT);
	ADC_CH0_GPIO_SET = _BV(ADC_CH0_GPIO_BIT);
}

void adc_ch0_clr(void)
{
	CLEARBIT(ADC_CH0_PINSEL_REG, ADC_CH0_PINSEL_BIT0);
	CLEARBIT(ADC_CH0_PINSEL_REG, ADC_CH0_PINSEL_BIT1);
	SETBIT(ADC_CH0_GPIO_DIR, ADC_CH0_GPIO_BIT);
	ADC_CH0_GPIO_CLR = _BV(ADC_CH0_GPIO_BIT);
}

void adc_ch1_set(void)
{
	CLEARBIT(ADC_CH1_PINSEL_REG, ADC_CH1_PINSEL_BIT0);
	CLEARBIT(ADC_CH1_PINSEL_REG, ADC_CH1_PINSEL_BIT1);
	SETBIT(ADC_CH1_GPIO_DIR, ADC_CH1_GPIO_BIT);
	ADC_CH1_GPIO_SET = _BV(ADC_CH1_GPIO_BIT);
}

void adc_ch1_clr(void)
{
	CLEARBIT(ADC_CH1_PINSEL_REG, ADC_CH1_PINSEL_BIT0);
	CLEARBIT(ADC_CH1_PINSEL_REG, ADC_CH1_PINSEL_BIT1);
	SETBIT(ADC_CH1_GPIO_DIR, ADC_CH1_GPIO_BIT);
	ADC_CH1_GPIO_CLR = _BV(ADC_CH1_GPIO_BIT);
}

void adc_ch2_set(void)
{
	CLEARBIT(ADC_CH2_PINSEL_REG, ADC_CH2_PINSEL_BIT0);
	CLEARBIT(ADC_CH2_PINSEL_REG, ADC_CH2_PINSEL_BIT1);
	SETBIT(ADC_CH2_GPIO_DIR, ADC_CH2_GPIO_BIT);
	ADC_CH2_GPIO_SET = _BV(ADC_CH2_GPIO_BIT);
}

void adc_ch2_clr(void)
{
	CLEARBIT(ADC_CH2_PINSEL_REG, ADC_CH2_PINSEL_BIT0);
	CLEARBIT(ADC_CH2_PINSEL_REG, ADC_CH2_PINSEL_BIT1);
	SETBIT(ADC_CH2_GPIO_DIR, ADC_CH2_GPIO_BIT);
	ADC_CH2_GPIO_CLR = _BV(ADC_CH2_GPIO_BIT);
}

void adc_ch3_set(void)
{
	CLEARBIT(ADC_CH3_PINSEL_REG, ADC_CH3_PINSEL_BIT0);
	CLEARBIT(ADC_CH3_PINSEL_REG, ADC_CH3_PINSEL_BIT1);
	SETBIT(ADC_CH3_GPIO_DIR, ADC_CH3_GPIO_BIT);
	ADC_CH3_GPIO_SET = _BV(ADC_CH3_GPIO_BIT);
}

void adc_ch3_clr(void)
{
	CLEARBIT(ADC_CH3_PINSEL_REG, ADC_CH3_PINSEL_BIT0);
	CLEARBIT(ADC_CH3_PINSEL_REG, ADC_CH3_PINSEL_BIT1);
	SETBIT(ADC_CH3_GPIO_DIR, ADC_CH3_GPIO_BIT);
	ADC_CH3_GPIO_CLR = _BV(ADC_CH3_GPIO_BIT);
}
