#include "adc_select.h"

void adc_select_init(void)
{
	SETBIT(ADC_SELECT_DIR, ADC_SELECT_BIT);

	CLEARBITS(ADC_SELECT_PINSEL, ADC_SELECT_PINSEL_MASK);
	SETBITS(ADC_SELECT_PINSEL, ADC_SELECT_PINSEL_VALUE << ADC_SELECT_PINSEL_SHIFT);
}

void adc_select(int ch)
{
	if (ch)
		SETBIT(ADC_SELECT_SET, ADC_SELECT_BIT);
	else
		SETBIT(ADC_SELECT_CLR, ADC_SELECT_BIT);
}
